---
# This playbook deploys a simple standalone JBoss server.

#- include: site-pre.yml
 
- hosts: aws
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  roles:
    - apache 

