---
- name: Webserver Security Group Creation
  ec2_group:
    aws_access_key: "{{ aws_id }}"
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    name: "{{ aws_sec_group_name }}"
    description: "{{ aws_sec_group_dec }}"
    vpc_id: "{{ aws_default_vpc }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
  #register: secgrp
- name: Gather facts  on created security group
  ec2_group_facts:
    aws_access_key: "{{ aws_id }}"
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    filters:
      group-name: "{{ aws_sec_group_name }}"
  register: secgrp
- name: output
  debug: var=secgrp 

- copy: content="{{ secgrp }}" dest=/home/test/playbooks/aws-project/temp/secgrpinfo
  
